["gui"]
disconnect = "Awooo"
dismiss = "OwO"
dismiss_far = "T_T" # badly named
kicked = "Nowo way"
inventory = "What youw have"
cancel = "Cancwel"

["gui.options"]
enablereverb = "uwu UwU UWU"
mastervolume = "owo OwO OWO"
resourcepacks = "Fuw pattewn"

["gui.title"]
startsingleplayer = "Stawt Snglplr!!!"
startmultiplayer = "Stawt Multiplr!!!"
join = "Join"
options = "Lowoudness and stuwuf"
quit = "Teeheee I'm done playing owo"
ip = "ip"
port = "Port"
username = "My Fursona UwU"

["kick"]
generic = "OwOOO YOU DID AN OOPSIE DOO"
existingusername = "SOMEONE HAZ THAT NAME!"
wrongprotocol = "Prowocol wrongowo"
invalidusername = "UwU Namey Wamey Invalidy"
banned = "UwU admin wadmin got angyyyy"
closing = "The sever is clowsing"

["msg"]
joined = "&@15;%s joiwned the furcon!"
left = "&@15;%s lewft the furcon!"
opped = "&@15;%s is now an admin uwu."
deopped = "&@15;%s is no longer an admin uwu."
youhaveop = "&@15;Youw awe an admin, uwu"