# Swag language, fo shizzle

["gui"]
disconnect = "I'm outta here!"
dismiss = "Aight"
dismiss_far = "Aight, okay"
kicked = "Fo shame"
inventory = "Yo Swag!"
cancel = "Naw"

["gui.options"]
enablereverb = "Reverb, yo"
mastervolume = "Master Volume: %d%%"
resourcepacks = "The lookz, yo"

["gui.title"]
startsingleplayer = "Go solo, yo"
startmultiplayer = "Whit th' homies"
join = "Aight, let's play"
options = "Gotta change"
quit = "Aight I'm out"
ip = "IP"
port = "Port"
username = "Yo name, dawg"

["kick"]
generic = "Fo shame, Fo shame."
existingusername = "Ayo dawg, don't try-ta use someone else's name! Fo shame!"
wrongprotocol = "Protocol's all outta whack, yo."
invalidusername = "Your name just ain't right!"
banned = "You know you ain't welcome here, dawg."
closing = "Server's closing, dawg."

["msg"]
joined = "&@15;Ayo, welcome %s!"
left = "Ayo, %s is outta here!"
opped = "Ayo, %s is opped!"
deopped = "Ayo, %s is no longer opped."
youhaveop = "&@15;Ey, you're opped"