["gui"]
disconnect = "Return to Port"
dismiss = "Go Back!"
dismiss_far = "Continue Sailin'"
kicked = "Thrown Overboard!"
inventory = "Booty..."
cancel = "Cancel"

["gui.options"]
enablereverb = "Listen more"
mastervolume = "Deafness: %d%%"
resourcepacks = "Paint for th' ship"

["gui.title"]
startgame = "Weigh anchor"
options = "Options!"
quit = "Leave th' seas"
ip = "Th' Destination"
port = "Pirate's Password"
username = "Captain Name!"

["kick"]
generic = "Filthy Landlubber!"
existingusername = "Yarr captain's name is already taken!"
protocolmismatch = "Yer' speakin' jibberish, lad."
invalidusername = "The captain name given is not valid."
banned = "Yer' banned from this ship!"
closing = "Th' ship's closing!"

["msg"]
joined = "%s has come aboard!"
left = "%s has left the ship!"
opped = "%s is a matey now!"
deopped = "%s is no longer a matey."
youhaveop = "You are a matey of the ship!"