# Small pieces of documentation, GO!
# [Sound event name] - The naming convention is dot-seperated, but isn't hard-enforced.
# type = string - Right now there's just block, but it will expand to other areas, used for volume meters.
# appendSounds = bool - If true, we add the sounds to the pool rather than replace. Only good for resource packs really. Assumed false.
# sounds = [] - Array of sound names to load
# pitch = [a,b] - The pitch played will be between a and b, if absent assumed [1,1]

##########################################
# UI And Miscellaneous                   #
##########################################

["soundtest"]
type = "block"
appendSounds = false
sounds = ["red.ogg", "green.ogg", "blue.ogg"]
pitch = [1.0,2.0]

["game.music"]
type = "music"
appendSounds = false
sounds = ["music/mojyjes.ogg", "music/shestenar.ogg", "music/isteke.ogg", "music/ino.ogg"]
pitch = [1.0]

["ui.click"]
type = "ui"
appendSounds = false
sounds = ["uiclick.ogg"]
pitch = [0.9, 1.1]

["ui.check"]
type = "ui"
appendSounds = false
sounds = ["uiclick.ogg"]
pitch = [0.9]

["ui.uncheck"]
type = "ui"
appendSounds = false
sounds = ["uiclick.ogg"]
pitch = [0.75]

["ui.tick"]
type = "ui"
appendSounds = false
sounds = ["uitick.ogg"]
pitch = [0.8, 1.2]

##########################################
# Breaking Sounds                        #
##########################################

["block.break.stone"]
type = "block"
appendSounds = false
sounds = [ "breakstone.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.loose"]
type = "block"
appendSounds = false
sounds = [ "breakloose.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.wood"]
type = "block"
appendSounds = false
sounds = [ "breakwood.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.glass"]
type = "block"
appendSounds = false
sounds = [ "breakglass.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.organic"]
type = "block"
appendSounds = false
sounds = [ "breakorganic.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.dust"]
type = "block"
appendSounds = false
sounds = [ "breaksand.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.fabric"]
type = "block"
appendSounds = false
sounds = [ "breakfabric.ogg" ]
pitch = [ 0.6, 1.2 ]

##########################################
# Placing Sounds                         #
##########################################

["block.place.stone"]
type = "block"
appendSounds = false
sounds = [ "placestone.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.loose"]
type = "block"
appendSounds = false
sounds = [ "placeloose.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.wood"]
type = "block"
appendSounds = false
sounds = [ "placewood.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.glass"]
type = "block"
appendSounds = false
sounds = [ "placestone.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.organic"]
type = "block"
appendSounds = false
sounds = [ "placeorganic.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.dust"]
type = "block"
appendSounds = false
sounds = [ "placesand.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.fabric"]
type = "block"
appendSounds = false
sounds = [ "breakfabric.ogg" ]
pitch = [ 0.6, 1.2 ]

##########################################
# Footstep Sounds                        #
##########################################

["block.step.stone"]
type = "block"
appendSounds = false
sounds = [ "placestone.ogg", "breakstone.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.loose"]
type = "block"
appendSounds = false
sounds = [ "placeloose.ogg", "breakloose.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.wood"]
type = "block"
appendSounds = false
sounds = [ "placewood.ogg", "breakwood.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.glass"]
type = "block"
appendSounds = false
sounds = [ "placestone.ogg", "breakstone.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.organic"]
type = "block"
appendSounds = false
sounds = [ "placeorganic.ogg", "breakorganic.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.dust"]
type = "block"
appendSounds = false
sounds = [ "placesand.ogg", "breaksand.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.fabric"]
type = "block"
appendSounds = false
sounds = [ "breakfabric.ogg" ]
pitch = [ 0.9, 1.1 ]

##########################################
# Entity Sounds                          #
##########################################

["entity.fastsmack"]
type = "entity"
appendSounds = false
sounds = [ "smack.ogg" ]
pitch = [ 1.0, 1.2 ]

["entity.swim"]
type = "entity"
appendSounds = false
sounds = [ "swim1.ogg", "swim2.ogg" ]
pitch = [ 0.7, 1.3 ]

["entity.splash"]
type = "entity"
appendSounds = false
sounds = [ "splash.ogg" ]
pitch = [ 0.7, 1.3 ]

##########################################
# Misc. Sounds                           #
##########################################

["block.soundmaker.use"]
type = "block"
appendSounds = false
sounds = [ "red.ogg", "green.ogg", "blue.ogg", "swim1.ogg", "swim2.ogg", "splash.ogg", "smack.ogg", "place.ogg", "break.ogg", "placestone.ogg", "placeloose.ogg", "placewood.ogg", "placeorganic.ogg", "placesand.ogg", "breaksand.ogg", "breakstone.ogg", "breakloose.ogg", "breakwood.ogg", "breakfabric.ogg", "breakorganic.ogg", "uiclick.ogg", "uitick.ogg" ]
pitch = [ 0.9, 1.1 ]