["gui"]
disconnect = "Lyz"
dismiss = "Aof"
dismiss_far = "Aof" # badly named
kicked = "Nao shaoth geedhia!" # TODO: no translation yet
inventory = "Jaz aof"
cancel = "Nao"

["gui.options"]
enablereverb = "Juf iakaof"
mastervolume = "Shtoig voijee: %d%%"
resourcepacks = "Shu reef"

["gui.title"]
startgame = "Shtoirth"
options = "Oisrr geexogf"
quit = "Lyz"
ip = "IP"
port = "Port"
username = "Naa"

["kick"]
generic = "Nao shaoth geedhia."
existingusername = "Naa jufeeg!"
wrongprotocol = "Protocol naotrui."
invalidusername = "Naa naotrui."
banned = "Ja naokoi."