["gui"]
disconnect = "Trennen"
dismiss = "Ablehnen"
dismiss_far = "Ablehnen"
kicked = "Gekickt"
inventory = "Inventar..."
cancel = "Abbrechen"

["gui.options"]
enablereverb = "Reverb aktivieren"
mastervolume = "Masterlautstärke (%d%%)"
resourcepacks = "Resourcepacks"

["gui.title"]
startsingleplayer = "Einzelspieler starten"
startmultiplayer = "Mehrspieler starten"
join = "Beitreten"
options = "Optionen"
quit = "Beenden"
ip = "IP Adresse"
port = "Port"
username = "Benutzername"

["kick"]
generic = "Du wurdest gekickt."
existingusername = "Der Benutzername existiert bereits."
wrongprotocol = "Falsches Protokoll."
invalidusername = "Der Benutzername ist ungültig."
banned = "Du wurdest gebannt."
closing = "Beende..."


["msg"]
joined = "&@15;%s ist dem Spiel beigetreten."
left = "&@15;%s hat das Spiel verlassen."
opped = "&@15;%s wurde opped."
deopped = "&@15;%s wurde deopped."
youhaveop = "&@15;Du hast Operatorrechte auf diesem Server."