# Norsk

["gui"]
disconnect = "Koble fra"
dismiss = "Avslutt"
dismiss_far = "Avslutt"
kicked = "Kastet ut"
inventory = "Inventar..."
cancel = "Avbryt"

["gui.options"]
enablereverb = "Aktiver høyttalerev"
mastervolume = "Mastervolum (%d%%)"
resourcepacks = "Ressurspakker"

["gui.title"]
startsingleplayer = "Start enkeltspiller"
startmultiplayer = "Start flerspiller"
join = "Bli med"
options = "Innstillinger"
quit = "Avslutt"
ip = "IP adresse"
port = "Port"
username = "Brukernavn"

["kick"]
generic = "Ingen årsak gitt"
existingusername = "Brukernavnet finnes allerede"
wrongprotocol = "Feil protokoll"
invalidusername = "Ugyldig brukernavn"
banned = "Du er bannet!"
closing = "Lukker..."


["msg"]
joined = "&@15;%s har koblet til."
left = "&@15;%s har forlatt spillet."
opped = "&@15;%s har blitt oppet."
deopped = "&@15;%s har blitt deoppet."
youhaveop = "&@15;Du har operator rettigheter på denne tjeneren."