# Portuguese

["gui"]
disconnect = "Desconectar"
dismiss = "Desistir"
dismiss_far = "Desistir"
kicked = "Expulsado"
inventory = "Inventário"
cancel = "Cancelar"

["gui.options"]
enablereverb = "Ativar Reverb"
mastervolume = "Volume Mestre (%d%%)"
resourcepacks = "Pacotes de Recursos"

["gui.title"]
startsingleplayer = "Iniciar Singleplayer"
startmultiplayer = "Iniciar Multiplayer"
join = "Entrar"
options = "Opçoes" # TODO: Typo, we don't have the õ symbol
quit = "Sair"
ip = "IP do Servidor"
port = "Port"
username = "Nome de Usuário"

["kick"]
generic = "Nenhuma razão especificada"
existingusername = "Nome de usuário já existente"
wrongprotocol = "Versão de protocolo incorreta"
invalidusername = "Nome de usuário inválido"
banned = "Banido"
closing = "Fechando conexão"


["msg"]
joined = "&@15;%s entrou no jogo."
left = "&@15;%s saiu do jogo."
opped = "&@15;%s foi promovido a moderador."
deopped = "&@15;%s foi demitido."
youhaveop = "&@15;Você é um moderador neste servidor."