# Small pieces of documentation, GO!
# [Sound event name] - The naming convention is dot-seperated, but isn't hard-enforced.
# type = string - Right now there's just block, but it will expand to other areas, used for volume meters.
# appendSounds = bool - If true, we add the sounds to the pool rather than replace. Only good for resource packs really. Assumed false.
# sounds = [] - Array of sound names to load
# pitch = [a,b] - The pitch played will be between a and b, if absent assumed [1,1]

##########################################
# UI And Miscellaneous                   #
##########################################

["soundtest"]
type = "block"
appendSounds = false
sounds = ["sound/red.ogg", "sound/green.ogg", "sound/blue.ogg"]
pitch = [1.0,2.0]

["game.music"]
type = "music"
appendSounds = false
sounds = ["sound/music/mojyjes.ogg", "sound/music/shestenar.ogg", "sound/music/isteke.ogg"]
pitch = [1.0]

["ui.click"]
type = "ui"
appendSounds = false
sounds = ["sound/uiclick.ogg"]
pitch = [0.9, 1.1]

##########################################
# Breaking Sounds                        #
##########################################

["block.break.stone"]
type = "block"
appendSounds = false
sounds = [ "sound/breakstone.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.loose"]
type = "block"
appendSounds = false
sounds = [ "sound/breakloose.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.wood"]
type = "block"
appendSounds = false
sounds = [ "sound/breakwood.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.glass"]
type = "block"
appendSounds = false
sounds = [ "sound/breakglass.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.organic"]
type = "block"
appendSounds = false
sounds = [ "sound/breakorganic.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.break.dust"]
type = "block"
appendSounds = false
sounds = [ "sound/breaksand.ogg" ]
pitch = [ 0.6, 1.2 ]

##########################################
# Placing Sounds                         #
##########################################

["block.place.stone"]
type = "block"
appendSounds = false
sounds = [ "sound/placestone.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.loose"]
type = "block"
appendSounds = false
sounds = [ "sound/placeloose.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.wood"]
type = "block"
appendSounds = false
sounds = [ "sound/placewood.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.glass"]
type = "block"
appendSounds = false
sounds = [ "sound/placestone.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.organic"]
type = "block"
appendSounds = false
sounds = [ "sound/placeorganic.ogg" ]
pitch = [ 0.6, 1.2 ]

["block.place.dust"]
type = "block"
appendSounds = false
sounds = [ "sound/placesand.ogg" ]
pitch = [ 0.6, 1.2 ]

##########################################
# Footstep Sounds                        #
##########################################
["block.step.stone"]
type = "block"
appendSounds = false
sounds = [ "sound/placestone.ogg", "sound/breakstone.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.loose"]
type = "block"
appendSounds = false
sounds = [ "sound/placeloose.ogg", "sound/breakloose.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.wood"]
type = "block"
appendSounds = false
sounds = [ "sound/placewood.ogg", "sound/breakwood.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.glass"]
type = "block"
appendSounds = false
sounds = [ "sound/placestone.ogg", "sound/breakstone.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.organic"]
type = "block"
appendSounds = false
sounds = [ "sound/placeorganic.ogg", "sound/breakorganic.ogg" ]
pitch = [ 0.9, 1.1 ]

["block.step.dust"]
type = "block"
appendSounds = false
sounds = [ "sound/placesand.ogg", "sound/breaksand.ogg" ]
pitch = [ 0.9, 1.1 ]